site_name: My Docs

nav:
  - Home: index.md
  - Syntax:
      - Links: "syntax/link/links.md"
  - "Our contacts":
      - "In Russia": "contacts/russia.md"
      - "In USA": "contacts/usa.md"
  - About: about.md

#theme: readthedocs
#theme: material

markdown_extensions:
  - toc:
      permalink: true
