CREATE TABLE dbo.CONSUMER_DB_CAR (
    model VARCHAR(20),
    year INTEGER
);
INSERT INTO dbo.CONSUMER_DB_CAR(model, year) VALUES('BMW', 2020);
INSERT INTO dbo.CONSUMER_DB_CAR("model", "year") VALUES('Audi', 2019);
SELECT * FROM dbo.CONSUMER_DB_CAR;