version: '3'
services:
  master-service:
    container_name: hadoop-cluster-master
    build:
      context: context
    ports:
      - "8088:8088"
      - "50070:50070"
      - "9000:9000"
      - "50075:50075"
    hostname: master-service
    entrypoint: ./entrypoint_master.sh
    volumes:
      - /tmp/logs-hadoop:/tmp/logs
  slave-service:
    container_name: hadoop-cluster-slave
    build:
      context: context
    ports:
      - "51075:50075"
      - "51070:50070"
    links:
      - master-service
    depends_on:
      - master-service
    tty: true
    hostname: slave-service
    entrypoint: ./entrypoint_slave.sh
