apiVersion: v1
kind: Pod
metadata:
  name: sealed-secret-env-pod
spec:
  containers:
    - name: sealed-secret-env-container
      image: alpine
      command: [ "sh", "-c", "echo $USER; echo $PASS; while true; do echo 'Hello, World!'; sleep 5; done" ]
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: sealed-secret-env-secret
              key: username
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: sealed-secret-env-secret
              key: password
  restartPolicy: OnFailure