# Install packages with apt
---
- hosts: all
  tasks:
    - name: Add a repository
      apt_repository:
        repo: 'ppa:hluk/copyq'
        state: present
    - name: Update cache and Upgrade packages
      apt: 
        update_cache: yes
        upgrade: yes
        autoremove: true
    - name: Install curl and krita
      apt: 
        pkg:
          - curl
          - krita
        autoremove: true
      