# Work with directories
---
- hosts: all
  tasks:
    - name: Create a directory
      file:
        path: ./tmp
        state: directory
    - name: Delete a directory
      file:
        path: ./tmp
        state: absent
