version: '3'
services:
  master-service:
    container_name: hadoop3-cluster-master
    image: hadoop3-cluster-master
    build:
      context: context
      args:
        - HADOOP_VERSION=${HADOOP_VERSION}
        - SPARK_VERSION=${SPARK_VERSION}
        - SPARK_BASE_IMAGE_TAG=${SPARK_BASE_IMAGE_TAG}
    hostname: master-service
    entrypoint: ./entrypoint_master.sh
    volumes:
      - /tmp/hadoop3-cluster-logs/master:/tmp/logs
  slave-service-1:
    container_name: hadoop3-cluster-slave-1
    image: hadoop3-cluster-slave-1
    build:
      context: context
      args:
        - HADOOP_VERSION=${HADOOP_VERSION}
        - SPARK_VERSION=${SPARK_VERSION}
        - SPARK_BASE_IMAGE_TAG=${SPARK_BASE_IMAGE_TAG}
    hostname: slave-service-1
    links:
      - master-service
    depends_on:
      - master-service
    tty: true
    entrypoint: ./entrypoint_slave_1.sh
    volumes:
      - /tmp/hadoop3-cluster-logs/slave-1:/tmp/logs
  slave-service-2:
    container_name: hadoop3-cluster-slave-2
    image: hadoop3-cluster-slave-2
    build:
      context: context
      args:
        - HADOOP_VERSION=${HADOOP_VERSION}
        - SPARK_VERSION=${SPARK_VERSION}
        - SPARK_BASE_IMAGE_TAG=${SPARK_BASE_IMAGE_TAG}
    hostname: slave-service-2
    links:
      - master-service
      - slave-service-1
    depends_on:
      - master-service
      - slave-service-1
    tty: true
    entrypoint: ./entrypoint_slave_2.sh
    volumes:
      - /tmp/hadoop3-cluster-logs/slave-2:/tmp/logs
networks:
  default:
    name: hadoop3-cluster-network
