# Print debug info from a template (with `jinja2.ext.debug` Jinja extension)
# The extension is attached in `ansible.cfg`
---
- hosts: all
  vars:
    server: go.com
  pre_tasks:
    - file:
        path: ./tmp
        state: absent
    - file:
        path: ./tmp
        state: directory
  tasks:
    - template:
         src: config.ini.j2
         dest: ./tmp/config.ini
