version: '3'
services:
  master-service:
    container_name: hdfs-kerberos-cluster-master
    build:
      context: context
      args:
        - HADOOP_BASE_IMAGE=${HADOOP_BASE_IMAGE}
    hostname: master.yaal.ru
    entrypoint: ./entrypoint_master.sh
    links:
      - kdc
    depends_on:
      - kdc
    volumes:
      - kerberos:/tmp/kerberos
  slave-service-1:
    container_name: hdfs-kerberos-cluster-slave-1
    build:
      context: context
      args:
        - HADOOP_BASE_IMAGE=${HADOOP_BASE_IMAGE}
    hostname: slave1.yaal.ru
    links:
      - master-service
      - kdc
    depends_on:
      - master-service
    tty: true
    entrypoint: ./entrypoint_slave_1.sh
    volumes:
      - kerberos:/tmp/kerberos
  slave-service-2:
    container_name: hdfs-kerberos-cluster-slave-2
    build:
      context: context
      args:
        - HADOOP_BASE_IMAGE=${HADOOP_BASE_IMAGE}
    hostname: slave2.yaal.ru
    links:
      - master-service
      - slave-service-1
      - kdc
    depends_on:
      - master-service
      - slave-service-1
    tty: true
    entrypoint: ./entrypoint_slave_2.sh
    volumes:
      - kerberos:/tmp/kerberos
  kdc:
    container_name: hdfs-kerberos-cluster-kdc
    build:
      context: kdc_context
    hostname: kdc.yaal.ru
    tty: true
    volumes:
      - kerberos:/tmp/kerberos
networks:
  default:
    name: hdfs-kerberos-cluster-network
volumes:
  kerberos: