version: '3'
services:
  master-service:
    container_name: hadoop-cluster-master
    image: hadoop-cluster-master
    build:
      context: context
      args:
        - SPARK_BASE_IMAGE=${SPARK_BASE_IMAGE}
    hostname: master-service
    entrypoint: ./entrypoint_master.sh
    volumes:
      - /tmp/hadoop-cluster-logs/master:/tmp/logs
    depends_on:
      - postgres
  slave-service-1:
    container_name: hadoop-cluster-slave-1
    image: hadoop-cluster-slave-1
    build:
      context: context
      args:
        - SPARK_BASE_IMAGE=${SPARK_BASE_IMAGE}
    hostname: slave-service-1
    links:
      - master-service
    depends_on:
      - master-service
    tty: true
    entrypoint: ./entrypoint_slave_1.sh
    volumes:
      - /tmp/hadoop-cluster-logs/slave-1:/tmp/logs
  slave-service-2:
    container_name: hadoop-cluster-slave-2
    image: hadoop-cluster-slave-2
    build:
      context: context
      args:
        - SPARK_BASE_IMAGE=${SPARK_BASE_IMAGE}
    hostname: slave-service-2
    links:
      - master-service
      - slave-service-1
    depends_on:
      - master-service
      - slave-service-1
    tty: true
    entrypoint: ./entrypoint_slave_2.sh
    volumes:
      - /tmp/hadoop-cluster-logs/slave-2:/tmp/logs
  postgres:
    container_name: hadoop-postgres
    image: postgres:13
    hostname: hadoop-postgres
    tty: true
    environment:
      POSTGRES_PASSWORD: the_postgres_pass
networks:
  default:
    name: hadoop-cluster-network
