apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hello-world-template
  annotations:
    description: "Hello world"
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: hello-world-pod
    spec:
      containers:
        - image: alpine
          name: alpine-container
          command: [ "sh", "-c", "while true; do echo 'Hello, World!'; sleep 3; done" ]
labels:
  app: hello-world
