envlist = ["3.12.7"]

[env_run_base]
description = "run unit tests"
passenv = ["*"]
deps = [
    "pytest>=8",
    "pytest-sugar",
    "pytest-qt"
]
commands = [["pytest", "-m", "not integration", "{posargs:tests}"]]

[env.integration]
commands = [["pytest", "-m", "integration", "{posargs:tests}"]]