apiVersion: v1
kind: Secret
metadata:
  name: secret-projection-secret
type: Opaque
data:
  username: bXlfdm9sdW1lX3VzZXJuYW1l
  password: bXlfdm9sdW1lX3Bhc3N3b3Jk
  key: bXlfa2V5
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-projection-pod
spec:
  containers:
  - name: secret-projection-container
    image: alpine
    command: [ "sh", "-c", "echo Username: $(cat /etc/creds/user/username.txt); echo Password: $(cat /etc/creds/user/password.txt); echo Key: $(cat /etc/creds/keys/key.txt); while true; do echo 'Hello, World!'; sleep 5; done" ]
    volumeMounts:
    - name: credentials
      mountPath: "/etc/creds"
      readOnly: true
  volumes:
  - name: credentials
    secret:
      secretName: secret-projection-secret
      items:
      - key: username
        path: user/username.txt
      - key: password
        path: user/password.txt
      - key: key
        path: keys/key.txt
  restartPolicy: OnFailure