@startuml
'https://plantuml.com/activity-diagram-beta#772273da3919bcd1

title Grouping

@startuml
start

group #lightGreen Initialization {
    :read config file;
    :init internal variable;
}

group Running the process {
    :wait for user interaction;
    :print information;
}

stop
@enduml
