# Use "include_vars" with template
---
- hosts: all
  pre_tasks:
    - file:
        path: ./tmp
        state: absent
    - file:
        path: ./tmp
        state: directory
  tasks:
    - name: Include vars
      include_vars: 
        file: vars.yaml    
    - name: Render a template
      template:
         src: config.ini.j2
         dest: ./tmp/config.ini
