version: '3'
services:
  server-service:
    container_name: secret-container
    image: alpine:latest
    secrets:
      - my_secret
    command: cat /run/secrets/my_secret
secrets:
  my_secret:
    file: ./my_secret.txt
