@startuml
'https://plantuml.com/activity-diagram-beta

title "repeat" loop which uses a full action as repeat target
start
repeat :foo as starting label;
  :read data;
  :generate diagrams;
backward:This is backward;
repeat while (more data?)
stop

@enduml
