@startuml
'https://plantuml.com/activity-diagram-beta

title "if-else" condition
start
if (Graphviz installed?) then (yes)
  :process all diagrams;
else (no)
  :process only activity diagrams;
endif
stop

@enduml
