apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-as-file-cm
data:
  game.properties: |
    city.name=SPb
    city.established=1703
  ui.properties: |
    color=green
---
apiVersion: v1
kind: Pod
metadata:
  name: config-map-as-file-pod
spec:
  containers:
  - name: config-map-as-file-container
    image: alpine
    command: [ "sh", "-c", "echo Game: $(cat /config/game.properties); echo UI: $(cat /config/ui.properties); while true; do echo 'Hello, World!'; sleep 5; done" ]
    volumeMounts:
      - name: config-map-volume
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config-map-volume
    configMap:
      name: config-map-as-file-cm
  restartPolicy: OnFailure