Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: kata-role-lambda-function-inline
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: kata-f-lambda-function-inline
      Runtime: python3.14
      Role: !GetAtt ExecutionRole.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          def handler(event, context):
            return 'Hello, World!'