apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  template:
    spec:
      containers:
      - name: hello-world-job-container
        image: hello-world
      restartPolicy: OnFailure
  backoffLimit: 4

# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: hello
# spec:
#   schedule: "*/1 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: hello
#             image: busybox
#             args:
#             - /bin/sh
#             - -c
#             - date; echo Hello from the Kubernetes cluster
#           restartPolicy: OnFailure