# Control whitespaces
# Docs: https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control
---
- hosts: all
  pre_tasks:
    - file:
        path: ./tmp
        state: absent
    - file:
        path: ./tmp
        state: directory
  tasks:
    - template:
         src: config.ini.j2
         dest: ./tmp/config.ini
    - debug:
        msg: "{{ lookup('file', './tmp/config.ini') }}"
