unit_tag: str = 'en::unit*'
absent_synonym1_tag: str = '~api::absent::synonym1'
absent_synonyms_tag: str = '~api::absent::synonyms'
absent_antonym1_tag: str = '~api::absent::antonym1'
absent_antonyms_tag: str = '~api::absent::antonyms'
