-- CASE (CONDITIONAL FUNCTION)
SELECT CASE WHEN 1 > 0 THEN 'BIG' ELSE 'SMALL' END;

SELECT name, CASE WHEN gender = 1 THEN 'MALE' ELSE 'FEMALE' END FROM (
    SELECT 'John' AS name, 1 AS gender
    UNION ALL
    SELECT 'Jane', 0
    UNION ALL
    SELECT 'Jim', 1
) AS t
