version: '3'
services:
  master:
    build:
      context: context
      target: spark
      args:
        HADOOP_BUILD_VERSION: $HADOOP_BUILD_VERSION
        SPARK_VERSION: $SPARK_VERSION
    container_name: spark-standalone-cluster-master
    hostname: spark-standalone-cluster-master
    entrypoint: ./entrypoint_master.sh
    volumes:
      - livy_shared:/shared
  slave-1:
    build:
      context: context
      target: spark
      args:
        HADOOP_BUILD_VERSION: $HADOOP_BUILD_VERSION
        SPARK_VERSION: $SPARK_VERSION
    container_name: spark-standalone-cluster-slave-1
    hostname: spark-standalone-cluster-slave-1
    entrypoint: ./entrypoint_slave_1.sh
    depends_on:
      - master
    volumes:
      - livy_shared:/shared
  slave-2:
    build:
      context: context
      target: spark
      args:
        HADOOP_BUILD_VERSION: $HADOOP_BUILD_VERSION
        SPARK_VERSION: $SPARK_VERSION
    container_name: spark-standalone-cluster-slave-2
    hostname: spark-standalone-cluster-slave-2
    entrypoint: ./entrypoint_slave_2.sh
    depends_on:
      - master
    volumes:
      - livy_shared:/shared
  livy:
    build:
      context: context
      target: livy
      args:
        HADOOP_BUILD_VERSION: $HADOOP_BUILD_VERSION
        SPARK_VERSION: $SPARK_VERSION
        LIVY_VERSION: $LIVY_VERSION
    container_name: spark-standalone-cluster-livy
    hostname: spark-standalone-cluster-livy
    entrypoint: ./entrypoint.sh
    depends_on:
      - master
    volumes:
      - livy_shared:/shared
networks:
  default:
    name: spark-standalone-cluster-network
volumes:
  livy_shared:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aleks/tmp/livy_shared