@startuml
'https://plantuml.com/component-diagram

component CentOs7
file Hadoop2.7
component HadoopBaseImage
component HiveBaseImage
component SparkBaseImage
component HadoopCluster

HadoopBaseImage --> CentOs7
HadoopBaseImage --> Hadoop2.7
HiveBaseImage --> HadoopBaseImage
SparkBaseImage --> HiveBaseImage
HadoopCluster --> SparkBaseImage

@enduml