@startuml
'https://plantuml.com/component-diagram

rectangle CentOs7 {
    card "root:root"
}
rectangle CentOsUpdated7
rectangle HadoopBaseImage {
    card "hadoop:hadoop"
    card "hdfs:hadoop"
    card "yarn:hadoop"
    card "mapred:hadoop"
}
rectangle HiveBaseImage {
    card "hive:hadoop"
}
rectangle SparkBaseImage {
    card "spark:hadoop"
}

CentOsUpdated7 --> CentOs7
HadoopBaseImage --> CentOsUpdated7
HiveBaseImage --> HadoopBaseImage
YarnHdfsCluster --> HadoopBaseImage
YarnHdfsKerberosCluster --> HadoopBaseImage
SparkBaseImage --> HiveBaseImage
HadoopCluster --> SparkBaseImage

@enduml