apiVersion: v1
kind: Secret
metadata:
  name: secret-env-secret
type: Opaque
data:
  username: bXlfdXNlcg==
  password: bXlfcGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: secret-env-container
      image: alpine
      command: [ "sh", "-c", "echo $USER; echo $PASS; while true; do echo 'Hello, World!'; sleep 5; done" ]
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: secret-env-secret
              key: username
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: secret-env-secret
              key: password
  restartPolicy: OnFailure