# Using Filters for manipulating variables
---
- hosts: all
  tasks:
    - name: Set default value 
      vars:
        person: John
      debug:
        msg: "Has value: {{ person | default('Nobody') }}. Doesn't have value: {{ person_absents | default('Nobody') }}"
    - name: Convert YAML to JSON
      vars:
        yaml_text: |
          ---
          person:
              name: John
              age: 30
      debug:
        msg: "YAML: {{ yaml_text }}. JSON: {{ yaml_text | from_yaml | to_json }}"
    - name: Access a field from YAML
      vars:
        yaml_text: |
          ---
          person:
              name: John
              age: 30
      debug:
        msg: "Age: {{ (yaml_text | from_yaml).person.age }}"