# Use SdkMan role
# Docs: https://galaxy.ansible.com/comcast/sdkman
# Install: sudo ansible-galaxy install comcast.sdkman
# Run: sudo ansible-playbook module/roles/SdkMan/playbook.yml
---
- hosts: all
  gather_facts: yes
  roles:
    - role: comcast.sdkman
      sdkman_user: aleks
      sdkman_group: aleks
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: '17-open' }
        - { candidate: java, version: '11.0.12-open' }
        - { candidate: java, version: '8.0.302-open' }
        - { candidate: gradle, version: '7.3.3' }
        - { candidate: kotlin, version: '1.6.10' }
        - { candidate: maven, version: '3.8.4' }
        - { candidate: sbt, version: '1.6.2' }
        - { candidate: scala, version: '2.13.8' }
        - { candidate: scala, version: '3.1.1' }
      sdkman_defaults:
        java: '17-open'
        gradle: '7.3.3'
        kotlin: '1.6.10'
        maven: '3.8.4'
        sbt: '1.6.2'
        scala: '3.1.1'
        