apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - name: sidecar-container-1
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 1; done" ]
  - name: sidecar-container-2
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 1; done" ]
  restartPolicy: OnFailure
