@startuml

actor ActorA [
    Line 1
    Line 2
]
component ComponentA [
    Line 1
    Line 2
]
node NodeA {
    component ComponentB
    component ComponentC [
    ComponentC
    ----
        Line 1
        Line 2
    ]
}

action ActionA <<Stereotype>> [
    ActionA
    ----
    Line 1
    Line 2
    ====
    Line 3
    Line 4
    ....
    Line 5
    Line 6
]
@enduml