# Different scopes of variables
---
- hosts: all
  vars:
    my_playbook_var: John
  tasks:
    - name: Use a task viriable
      vars:
        my_task_var: Moscow
      debug:
        var: my_task_var
    - name: Use a playbook viriable
      debug:
        var: my_playbook_var
    - name: Block variables
      block:
        - name: Use a block viriable
          debug:
            var: my_block_var
      vars:
        my_block_var: the block
