apiVersion: v1
kind: Pod
metadata:
  name: pod-env-vars-pod
spec:
  containers:
    - name: pod-env-vars-container
      image: alpine
      command: [ "sh", "-c", "echo $USER; echo $PASS; while true; do echo 'Hello, World!'; sleep 5; done" ]
      env:
        - name: USER
          value: john
        - name: PASS
          value: password
        - name: MULTILINE1
          value: >
            multiline1_A
            multiline1_B
        - name: MULTILINE2
          value: |
            multiline2_A
            multiline2_B
        - name: MULTILINE3
          value: |+
            multiline3_A
            multiline3_B
        - name: MULTILINE4
          value: |-
            multiline4_A
            multiline4_B
  restartPolicy: OnFailure