apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernates-plain-java
  labels:
    app: kubernates-plain-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernates-plain-java
  template:
    metadata:
      labels:
        app: kubernates-plain-java
    spec:
      containers:
        - name: kubernates-plain-java
          image: kubernates-plain-java:1
