apiVersion: v1
kind: ConfigMap
metadata:
  name: examples-config-map
data:
  colorGood: purple
  colorBad: yellow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernates-config-map
  labels:
    app: kubernates-config-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernates-config-map
  template:
    metadata:
      labels:
        app: kubernates-config-map
    spec:
      containers:
        - name: kubernates-config-map
          image: kubernates-config-map:1
          env:
            - name: GOOD_COLOR
              valueFrom:
                configMapKeyRef:
                  name: examples-config-map
                  key: colorGood
            - name: BAD_COLOR
              valueFrom:
                configMapKeyRef:
                  name: examples-config-map
                  key: colorBad
