version: '3'
services:
  master-service:
    container_name: hdfs-master
    build:
      context: hadoop
      args:
        - HADOOP_BASE_IMAGE=${HADOOP_BASE_IMAGE}
    hostname: hdfs-master
    domainname: hdfs.yaal.ru
    entrypoint: ./entrypoint_master.sh
    links:
      - kdc
    depends_on:
      - kdc
    volumes:
      - kerberos:/tmp/kerberos
    privileged: true
  slave-service-1:
    container_name: hdfs-slave1
    build:
      context: hadoop
      args:
        - HADOOP_BASE_IMAGE=${HADOOP_BASE_IMAGE}
    hostname: hdfs-slave1
    domainname: hdfs.yaal.ru
    links:
      - master-service
      - kdc
    depends_on:
      - master-service
      - kdc
    tty: true
    entrypoint: ./entrypoint_slave_1.sh
    volumes:
      - kerberos:/tmp/kerberos
    privileged: true
  slave-service-2:
    container_name: hdfs-slave2
    build:
      context: hadoop
      args:
        - HADOOP_BASE_IMAGE=${HADOOP_BASE_IMAGE}
    hostname: hdfs-slave2
    domainname: hdfs.yaal.ru
    links:
      - master-service
      - slave-service-1
      - kdc
    depends_on:
      - master-service
      - slave-service-1
      - kdc
    tty: true
    entrypoint: ./entrypoint_slave_2.sh
    volumes:
      - kerberos:/tmp/kerberos
    privileged: true
  client:
    container_name: hdfs-client
    build:
      context: hadoop
      args:
        - HADOOP_BASE_IMAGE=${HADOOP_BASE_IMAGE}
    hostname: hdfs-client
    domainname: hdfs.yaal.ru
    links:
      - master-service
      - slave-service-1
      - kdc
    depends_on:
      - master-service
      - kdc
    tty: true
    entrypoint: ./entrypoint_client.sh
    volumes:
      - kerberos:/tmp/kerberos
    privileged: true
  kdc:
    container_name: hdfs-kdc
    build:
      context: kdc
    hostname: hdfs-kdc
    domainname: hdfs.yaal.ru
    tty: true
    volumes:
      - kerberos:/tmp/kerberos
  sserver:
    container_name: hdfs-sserver
    build:
      context: sserver
    hostname: hdfs-sserver
    domainname: hdfs.yaal.ru
    tty: true
    volumes:
      - kerberos:/tmp/kerberos
  sclient:
    container_name: hdfs-sclient
    build:
      context: sclient
    hostname: hdfs-sclient
    domainname: hdfs.yaal.ru
    tty: true
    volumes:
      - kerberos:/tmp/kerberos
networks:
  default:
    name: hdfs.yaal.ru
volumes:
  kerberos: