apiVersion: v1
kind: Service
metadata:
  name: kubernates-spring-boot-service
  labels:
    app: kubernates-spring-boot-service
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: kubernates-spring-boot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernates-spring-boot-deployment
  labels:
    app: kubernates-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernates-spring-boot
  template:
    metadata:
      labels:
        app: kubernates-spring-boot
    spec:
      containers:
        - name: kubernates-spring-boot
          image: kubernates-spring-boot:7
          ports:
            - containerPort: 8080
