apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: binary-to-stream-input-stream
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: binary-to-stream-build-config
  labels:
    app: binary-to-stream
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "binary-to-stream-input-stream:1"
