@startuml
'https://plantuml.com/deployment-diagram

node kdc.kerberos.yaal.ru {
    component KDC
    database {
        person "admin/admin@LOCAL.REALM" as AdminPrincipal
        person "sserver/sserver.kerberos.yaal.ru@LOCAL.REALM" as SServerPrincipal
        person "sclient/sclient.kerberos.yaal.ru@LOCAL.REALM" as SClientPrincipal
    }
    file kdc.conf
}
node sserver.kerberos.yaal.ru {
    component SServer
}
node sclient.kerberos.yaal.ru {
    component SClient
}
node SharedVolume {
    file krb5.conf
    file sserver.keytab
    file sclient.keytab
}

@enduml

