@startuml
title Destroy with a narrow
autoactivate on
Alice -> Bob ** : new
Alice -> Bob: Authentication Request
Alice <-- Bob: Authentication Response
Alice -> Bob !!: destroy
@enduml

@startuml
title Destroy without narrow
autoactivate on
create Alice
create Bob
Alice -> Bob: new
Bob --> Alice: Authentication Response
destroy Bob
@enduml
