@startuml

actor Actor
participant Participant
boundary Boundary
control Control
entity Entity
database Database
collections Collection
queue Queue

Actor -> Participant : To participant
Actor -> Boundary : To boundary
Actor -> Control : To control
Actor -> Entity : To entity
Actor -> Database : To database
Actor -> Collection : To collections
Actor -> Queue : To queue

@enduml
