@startuml
hide empty members

title Hide empty fields and methods

class Person {
    String name
    String getAddress()
}
class City {
    String name
}
class Country

Person -> City
City -> Country

@enduml