@startuml

title "Client Credentials Flow" scenario

autonumber

Client -> WebApp: Resource request\nhttp://localhost:35713/users
activate WebApp
WebApp -> AzureAd: Get Access Token\nby ClientId and ClientSecret
activate AzureAd
WebApp <-- AzureAd: Access Token
deactivate AzureAd
    WebApp -> WebApp: Prepare Resource
    activate WebApp
        WebApp -> AzureGraph: Get Users\nhttps://graph.microsoft.com/v1.0/users
        activate AzureGraph
        WebApp <-- AzureGraph: Users
        deactivate AzureGraph
    WebApp <-- WebApp: HTML
    deactivate WebApp
Client <-- WebApp: Resource
deactivate WebApp

@enduml