apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernates-secret
  labels:
    app: kubernates-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernates-secret
  template:
    metadata:
      labels:
        app: kubernates-secret
    spec:
      containers:
        - name: kubernates-secret
          image: kubernates-secret:1
          volumeMounts:
            - name: foo
              mountPath: "/etc/foo"
              readOnly: true
      volumes:
        - name: foo
          secret:
            secretName: mysecret