# Using Dictionary variables
---
- hosts: all
  vars:
    my_playbook_var: John
  tasks:
    - name: Create a dictionary variable
      vars:
        my_dict:
          name: John
          position: manager
          age: 30
      debug:
        var: my_dict
    - name: Create a dictionary variable (shorthand YAML syntax)
      vars:
        city_dict: { 'city': Moscow, 'established': 1147 }
      debug:
        var: city_dict
    - name: Access to element by dot notation
      vars:
        my_dict:
          name: John
          position: manager
          age: 30
      debug:
        msg: "Name: {{ my_dict.name }}, Position: {{ my_dict.position }}, Age: {{ my_dict.age }}"
    - name: Access to element by bracket notation
      vars:
        my_dict:
          name: John
          position: manager
          age: 30
      debug:
        msg: "Name: {{ my_dict['name'] }}, Position: {{ my_dict['position'] }}, Age: {{ my_dict['age'] }}"