CREATE TABLE PERSON(id BIGINT, name VARCHAR, age INTEGER);
INSERT INTO PERSON(id, name, age) VALUES (1, 'John', 35), (2, 'Jim', 30), (3, 'Mary', 25);
SELECT * FROM PERSON;
SELECT * FROM PERSON WHERE name LIKE 'J%';
DROP TABLE PERSON; 