SET AUTOCOMMIT FALSE;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON(id BIGINT, name VARCHAR);

INSERT INTO PERSON(id, name) VALUES (1, 'John');
COMMIT;
SELECT * FROM PERSON;
INSERT INTO PERSON(id, name) VALUES (2, 'Mary');
SELECT * FROM PERSON;
ROLLBACK;
SELECT * FROM PERSON;
