# Control whitespaces
---
- hosts: all
  pre_tasks:
    - file:
        path: ./tmp
        state: absent
    - file:
        path: ./tmp
        state: directory
  tasks:
    - template:
         src: config.ini.j2
         dest: ./tmp/config.ini

